### ISSUE TITLE
可以运行到欢迎登陆，然后输出一堆html后报错

### ISSUE THREAD

**Issue by rawchen** [always0108/Semi-automatic-Crawl-JWGL#1]
at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1447)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1333)
	at com.alibaba.fastjson.JSON.parse(JSON.java:152)
	at com.alibaba.fastjson.JSON.parse(JSON.java:162)
	at com.alibaba.fastjson.JSON.parse(JSON.java:131)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:223)
at ConnectJWGL.getStudentInformaction(ConnectJWGL.java:94)
at Main.main(Main.java:14)

**Comment by Morningstar-clon** [comment]
兄弟 解决了嘛 我也是这个问题

**Comment by rawchen** [comment]
解决了，看我这个项目https://github.com/rawchen/ZFsoft-XMUT-EducationalAdministrationSystem-API
